### ISSUE TITLE
Realtime Performance

### ISSUE THREAD

**Issue by MinjieLin** [nkwangyh/CubemapSLAM#1]
Firstly, this is a great slam system for large FOV camera. But the real-time performance is difficult to guarantee. 
On my PC(Intel® Core™ i7-7700 CPU @ 3.60GHz × 8), it costs about 120ms to process one frame. I tested the code and found out that most of the processing time is on ORB feature extraction. 

Personal suggestion: Use GPU to accelerate the ORB feature extraction process(like [https://github.com/yunchih/ORB-SLAM2-GPU2016-final](url)  )

**Comment by nkwangyh** [comment]
Thanks for the kind suggestions. You can also try to reduce the number of the feature to extract, for example, 1500 or 2000 features. Besides, the overlap between adjacent frames of large FoV cameras should be larger than that of pinhole cameras, which means the fps of the input video could be less than the normal standard (30fps). For example, the fps of the self-collected data sequence is about 10 fps to 15 fps.
