### ISSUE TITLE
Formula difference between the paper and this project code?

### ISSUE THREAD

**Issue by GnoyGnus** [nkwangyh/CubemapSLAM#5]
If you look at the 2.3 Subsection Epipolar Constructs on the Unit Sphere in the paper, sin_theta in the equation (10) is different from the project code below,
const float sin_theta = 1.0f / std::sqrt(1.0f/(tan3*tan3)+1);

I wonder if something is wrong or omitted.

**Comment by nkwangyh** [comment]
They are the same if you notice that the equation in the code could be derived by dividing both the numerator and denominator by \tan(\theta) of the equation.
